try:
    from PySide6.QtCore import (
        QAbstractTableModel,
        QItemSelection,
        QItemSelectionModel,
        QMimeData,
        QModelIndex,
        QObject,
        QPointF,
        QRectF,
        QSettings,
        QThread,
        QTimer,
        Qt,
        Signal,
        Slot,
    )
    from PySide6.QtGui import QColor, QDrag, QFont, QFontDatabase, QImage, QPainter, QPainterPath, QPen, QBrush, QPalette, QPixmap, QPolygonF, QTransform
    from PySide6.QtWidgets import (
        QApplication,
        QAbstractItemView,
        QCheckBox,
        QComboBox,
        QDialog,
        QDoubleSpinBox,
        QFileDialog,
        QFrame,
        QGridLayout,
        QGroupBox,
        QHBoxLayout,
        QInputDialog,
        QFormLayout,
        QLabel,
        QLineEdit,
        QListWidget,
        QListWidgetItem,
        QMainWindow,
        QMessageBox,
        QPushButton,
        QProgressBar,
        QScrollArea,
        QScrollArea,
        QSizePolicy,
        QSlider,
        QSpinBox,
        QStackedWidget,
        QTabWidget,
        QTableView,
        QTableWidget,
        QTableWidgetItem,
        QTextEdit,
        QToolTip,
        QVBoxLayout,
        QSpacerItem,
        QWidget,
    )
    QT_BINDING = "PySide6"
except ImportError:
    from PyQt6.QtCore import (
        QAbstractTableModel,
        QItemSelection,
        QItemSelectionModel,
        QMimeData,
        QModelIndex,
        QObject,
        QPointF,
        QRectF,
        QSettings,
        QThread,
        QTimer,
        Qt,
        pyqtSignal as Signal,
        pyqtSlot as Slot,
    )
    from PyQt6.QtGui import QColor, QDrag, QFont, QFontDatabase, QImage, QPainter, QPainterPath, QPen, QBrush, QPalette, QPixmap, QPolygonF, QTransform
    from PyQt6.QtWidgets import (
        QApplication,
        QAbstractItemView,
        QCheckBox,
        QComboBox,
        QDialog,
        QDoubleSpinBox,
        QFileDialog,
        QFrame,
        QGridLayout,
        QGroupBox,
        QHBoxLayout,
        QInputDialog,
        QFormLayout,
        QLabel,
        QLineEdit,
        QListWidget,
        QListWidgetItem,
        QMainWindow,
        QMessageBox,
        QPushButton,
        QProgressBar,
        QScrollArea,
        QScrollArea,
        QSizePolicy,
        QSlider,
        QSpinBox,
        QStackedWidget,
        QTabWidget,
        QTableView,
        QTableWidget,
        QTableWidgetItem,
        QTextEdit,
        QToolTip,
        QVBoxLayout,
        QSpacerItem,
        QWidget,
    )
    QT_BINDING = "PyQt6"
