try:
    from PySide6.QtCore import QMimeData, QObject, QPointF, QRectF, QSettings, QThread, Qt, Signal, Slot
    from PySide6.QtGui import QColor, QDrag, QFont, QFontDatabase, QPainter, QPen, QBrush, QPolygonF, QTransform
    from PySide6.QtWidgets import (
        QApplication,
        QAbstractItemView,
        QCheckBox,
        QComboBox,
        QDialog,
        QDoubleSpinBox,
        QFileDialog,
        QFrame,
        QGridLayout,
        QGroupBox,
        QHBoxLayout,
        QFormLayout,
        QLabel,
        QLineEdit,
        QListWidget,
        QListWidgetItem,
        QMainWindow,
        QMessageBox,
        QPushButton,
        QProgressBar,
        QScrollArea,
        QSizePolicy,
        QSlider,
        QSpinBox,
        QStackedWidget,
        QTabWidget,
        QTableWidget,
        QTableWidgetItem,
        QTextEdit,
        QToolTip,
        QVBoxLayout,
        QSpacerItem,
        QWidget,
    )
    QT_BINDING = "PySide6"
except ImportError:
    from PyQt6.QtCore import QMimeData, QObject, QPointF, QRectF, QSettings, QThread, Qt, pyqtSignal as Signal, pyqtSlot as Slot
    from PyQt6.QtGui import QColor, QDrag, QFont, QFontDatabase, QPainter, QPen, QBrush, QPolygonF, QTransform
    from PyQt6.QtWidgets import (
        QApplication,
        QAbstractItemView,
        QCheckBox,
        QComboBox,
        QDialog,
        QDoubleSpinBox,
        QFileDialog,
        QFrame,
        QGridLayout,
        QGroupBox,
        QHBoxLayout,
        QFormLayout,
        QLabel,
        QLineEdit,
        QListWidget,
        QListWidgetItem,
        QMainWindow,
        QMessageBox,
        QPushButton,
        QProgressBar,
        QScrollArea,
        QSizePolicy,
        QSlider,
        QSpinBox,
        QStackedWidget,
        QTabWidget,
        QTableWidget,
        QTableWidgetItem,
        QTextEdit,
        QToolTip,
        QVBoxLayout,
        QSpacerItem,
        QWidget,
    )
    QT_BINDING = "PyQt6"
